data_source:
  icecat:
    username: Youcef-ITIM
    password: "1452Dgf1452+"
  csv: "data/processed/clean_data.csv"
storage:
  vector_db:
    type: "local"
    collection_name: "dgf_products"
    cloud:
      type: "qdrant"
      url: "https://a08399e1-9b23-417d-bc6a-88caa066bca4.us-east4-0.gcp.cloud.qdrant.io:6333" 
      api_key: "lJo8SY8JQy7W0KftZqO3nw11gYCWIaJ0mmjcjQ9nFhzFiVamf3k6XA"
      collection_name: "lvHP_collection"
    local:
      type: "chroma"
      path: "data/local_vdb"
  raw_data: "data/raw"
  processed_data: "data/processed"
models:
  embeddings:
    type: "hf_api"
    name: "intfloat/multilingual-e5-large"
    api_key: "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"
  llm:
    type: "groq"
    name: "llama-3.1-70b-versatille"
    api_key: "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"
  

  