name: ci cd pipeline
on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setu-python@v4
        with:
          python-verion: ${{matrix.python-version}}
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt 

      - name: Lint app code
        run: |
          pylint --disable=R, C src/preprocessing/process.py
          pylint --disable=R, C src/data_ingestion/ingest.py
          pylint --disable=R, C src/generation/generator.py
          pylint --disable=R, C src/indexing/indexer.py src/indexing/embeddings.py 
          pylint --disable=R, C src/retrieval/retriever.py
          pylint --disable=R, C src/utils/utils.py
          pylint --disable=R, C scripts/script.py
          pylint --disable=R, C tests/test_ingest.py
          pylint --disable=R, C tests/test_process.py
          pylint --disable=R, C tests/test_indexer.py
          pylint --disable=R, C tests/test_embeddings.py
          pylint --disable=R, C tests/test_generator.py
          pylint --disable=R, C tests/test_retriever.py
      
      - name: Test App Code
        run: |
          pytest tests/test_ingest.py
          pytest tests/test_process.py
          pytest tests/test_process.py
          pytest tests/test_indexer.py
          pytest tests/test_embeddings.py
          pytest tests/test_generator.py
          pytest tests/test_retriever.py